server:
  port: 9292
  ssl:
    enable: true
    key-store-type: PKCS12
    key-store: https.p12
    key-store-password: vflfhf
    key-alias: students
spring:
  sql:
    init:
      platform: hsqldb
  jpa:
    defer-datasource-initialization: true